### PR TITLE
Add functionality to timeout the command

### LINKED ISSUE #1: Timeouts
Need to add timeouts on jobs. For example, if I run `ping 1.1.1.1` it will run forever, taking up a slot on a client.

### PR DESCRIPTION
**Pull request by mzfr**
Fixes #1 

Now if we send the command to the client it will timeout after two seconds. And on the client-side it will show something like the image below:

image

If you want I can increase the timeout count.

Also, I have formatted the code :)

### CODE REVIEW

**Comment by hakluke** [comment]
Hey mzfr! This is awesome - but many commands will legitimately take longer than 2 seconds to execute - is it possible to have the timeout set as a CLI argument?

**Comment by mzfr** [comment]
yeah I can add a new flag for `timeout`. Should I add it as `required` ? if not then what should be the default value?

**Comment by hakluke** [comment]
I would say that if no timeout flag is specified there should not be any timeout.

**Comment by hakluke** [comment]
Ah I see you went with required argument - that's totally fine with me too :)

**Comment by hakluke** [comment]
Merged!

**Pull request merged**
